# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Install system dependencies for playwright and MCP
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       build-essential wget gnupg unzip xvfb libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 \
       libxkbcommon0 libx11-xcb1 libxcb-dri3-0 libdrm2 libgbm1 libxcomposite1 libxrandr2 \
       libxdamage1 libxfixes3 libpango-1.0-0 libpangocairo-1.0-0 libopus0 libwayland-client0 libwayland-server0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install poetry
RUN pip install --no-cache-dir poetry

# Copy project metadata and install dependencies
COPY pyproject.toml poetry.lock* /app/
RUN poetry config virtualenvs.create false \
    && poetry install --no-root --without dev

# Copy application code
COPY . /app

# Install browser dependencies for playwright
RUN poetry run playwright install --with-deps

# Expose port if HTTP needed (unused for stdio)
EXPOSE 8000

# Set environment
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

# Default command: run MCP service over stdio
CMD ["python", "-m", "tiktok_mcp_service.main"]
